name: adguard_home_manager
description: AdGuard Home client

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.22.0+154

environment:
  sdk: '>=3.0.0 <4.0.0'

scripts:
  build:
    linux: "./linux/build-app.sh"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter   
  intl: any
  provider: ^6.1.5
  sqflite: ^2.3.2
  package_info_plus: 8.0.0
  animations: ^2.0.11
  device_info_plus: ^10.0.0
  uuid: ^4.5.1
  expandable: ^5.0.1
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.10
  percent_indicator: ^4.2.5
  flutter_markdown: ^0.7.7+1
  markdown: ^7.3.0
  html: ^0.15.6
  flutter_html: ^3.0.0
  sqlite3_flutter_libs: ^0.5.40
  sqflite_common_ffi: ^2.3.2
  contextmenu: ^3.0.0
  async: ^2.11.0
  sentry_flutter: ^8.0.0
  flutter_dotenv: ^6.0.0
  flutter_reorderable_list: ^1.3.1
  pie_chart: ^5.4.0
  segmented_button_slide: ^2.0.0
  http: ^1.5.0
  timezone: ^0.10.1
  flutter_custom_tabs: ^2.4.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  window_manager: ^0.3.9

dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.0
  flutter_gen: ^5.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/icon/icon-ios.png"
  image_path_android: "assets/icon/icon-android.png"
  adaptive_icon_foreground: "assets/icon/icon-android-adap.png"
  adaptive_icon_background: "#ffffff"
  macos:
    generate: true
    image_path: "assets/icon/icon-macos.png"
  windows:
    generate: true
    image_path: "assets/icon/icon-circle.png"

flutter_native_splash:
  android12: true
  image: assets/icon/icon-splash.png
  color: "#ffffff"
  color_dark: "#212121"
  image_dark: assets/icon/icon-splash.png

# The following section is specific to Flutter packages.
flutter:
  generate: true
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon-ios.png
    - assets/icon/icon-android-adap.png
    - assets/icon/icon-android.png
    - assets/icon/icon-splash.png
    - assets/icon/icon-macos.png
    - assets/icon/icon-circle.png
    - assets/icon/icon-circle-256.png
    - assets/icon/icon1024-white-center.png
    - assets/other/get_google_play.png
    - assets/resources/github.svg
    - assets/resources/google-play.svg
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
